package com.dermosphere.backend.repository;

import com.dermosphere.backend.entity.SystemAuditLog;
import org.springframework.data.jpa.repository.JpaRepository;

public interface AuditLogRepository extends JpaRepository<SystemAuditLog, Long> {
    // Basic CRUD operations are automatically generated by Spring Data JPA
}