server.port=${PORT:8081}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/dermosphere_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update

spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=1000000
spring.datasource.hikari.connection-timeout=9000000

management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.show-details=always

spring.servlet.multipart.max-file-size=10MB
spring.http.codecs.max-in-memory-size=10MB

logging.level.io.netty.resolver.dns=DEBUG
logging.level.reactor.netty=DEBUG